baseurl = "https://chezou.github.io/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Michiaki Ariga"
title = "chezou"
pygmentsuseclasses = true
#disqusShortname = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "Michiaki Ariga"
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "Don't panic"
Email = "chezou@gmail.com"
FaviconFile = "img/leaf.ico"
GATracker = "XYZ"
GitHub = "//github.com/chezou"
Initials = "ad" # Displayed on single post page; DEPRECATED in v0.3.0.
Lang = "en"
LinkedIn = "//linkedin.com/in/akiariga"
Twitter = "//twitter.com/chezou"
ExtraCssFiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.
